### ISSUE TITLE
ctypes.COMError

### ISSUE THREAD

**Issue by HLeonHong** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#20]
Please how could i solve this problem?

DirectX 版本: DirectX 12

pygame 2.1.2 (SDL 2.0.18, Python 3.8.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
Successfully loaded all settings
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Files\miniconda\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Files\miniconda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\LeonH\Documents\Euro Truck Simulator 2\Euro-Truck-Simulator-2-Lane-Assist-main\AppUI.py", line 27, in MainFileThread
    import MainFile
  File "C:\Users\LeonH\Documents\Euro Truck Simulator 2\Euro-Truck-Simulator-2-Lane-Assist-main\MainFile.py", line 49, in <module>
    import ets2LaneDetection as LaneDetection
  File "C:\Users\LeonH\Documents\Euro Truck Simulator 2\Euro-Truck-Simulator-2-Lane-Assist-main\ets2LaneDetection.py", line 123, in <module>
    camera = dxcam.create(region=monitor, output_color="BGR")
  File "D:\Files\miniconda\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "D:\Files\miniconda\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "D:\Files\miniconda\lib\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
  File "<string>", line 6, in __init__
  File "D:\Files\miniconda\lib\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x0000020CD5E329D0>
Traceback (most recent call last):
  File "D:\Files\miniconda\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "D:\Files\miniconda\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "D:\Files\miniconda\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by Tumppi066** [comment]
There are two common cases for this to occur.

1. You have a CPU with a GPU (for example a laptop.)
In this case you should go to the windows graphics settings and find python (or select the python.exe file directly) and make it run on the CPU instead of on your dedicated graphics.

2. The app is trying to capture outside of your current monitor.
In this case you should open up settings.json (or default.json on experimental) and change the capture x and y to zero.

Feel free to close the issue if this helps, otherwise I am here to answer any further questions.

**Comment by HLeonHong** [comment]
Is that right?
![图片](https://user-images.githubusercontent.com/44226142/218632064-e0e29973-38f5-44dc-9f14-1341d9d18621.png)

It seems that a new issue here, Help me again please 

pygame 2.1.2 (SDL 2.0.18, Python 3.8.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
Successfully loaded all settings
Loaded model of size : 34
D:\Files\miniconda\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\Files\miniconda\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
C:\Users\LeonH\Documents\Euro Truck Simulator 2\Euro-Truck-Simulator-2-Lane-Assist-main\ultrafastLaneDetector\ultrafastLaneDetector.py:180: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(lanes_points), np.array(lanes_detected)

**Comment by Tumppi066** [comment]
Yes that is correct. Seems that this issue is now related to this one. Like I said there I don't currently have time to fix it, but I will get to it sometime :)

https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/issues/19

**Comment by HLeonHong** [comment]
> 

Thanks
