### ISSUE TITLE
I cant Open because of python even if i have the correct version

### ISSUE THREAD

**Issue by SeanoBuTeTe** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#53]
C:\ETS2lane>python installer.py
C:\ETS2lane\installer.py:480: SyntaxWarning: invalid escape sequence '\.'
  os.system("rmdir /s /q app\.git")
 This app requires a Python version above 3.9.x and below 3.12.x to create the correct virtual environment.
 Please install another version and run the installer again.

**Comment by SeanoBuTeTe** [comment]
Where?

**Comment by SeanoBuTeTe** [comment]
in python 3.12?

**Comment by SeanoBuTeTe** [comment]
C:\laneassist>python installer.py
C:\laneassist\installer.py:480: SyntaxWarning: invalid escape sequence '\.'
  os.system("rmdir /s /q app\.git")
 This app requires a Python version above 3.9.x and below 3.12.x to create the correct virtual environment.
 Please install another version and run the installer again.
python -V

C:\laneassist>pause
Press any key to continue . . .

**Comment by SeanoBuTeTe** [comment]
>>> python -V
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>>

**Comment by SeanoBuTeTe** [comment]
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python -V
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined

**Comment by SeanoBuTeTe** [comment]
NVM i think i fixed IT
